src/Entity/NdSurat.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\NdSuratRepository")
 */
class NdSurat
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255,  nullable=true)
     */
    private $noSuratRt;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $noSuratRw;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $bodySurat;

    /**
     *
     * @ORM\Column(type="integer")
     */
    private $step;
    /**
     * @ORM\Column(type="string", length=255,nullable=true)
     */
    private $noSuratKeterangan;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $keterangan;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $tglSelesaiRT;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $tglSelesaiRW;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $tglSelesaiKelurahan;

    /**
     * @ORM\Column(type="datetime",nullable=true)
     */
    private $createdAt;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Penduduk")
     * @ORM\JoinColumn(nullable=false)
     */
    private $pemohonSurat;

    /**
     * @ORM\Column(type="string" , length=255)
     */
    private $noPengajuan;

    /**
     * @ORM\Column(type="integer")
     */
    private $Tipe;

    private $tembusandaftar;
    private $kepadadaftar;
    private $pemeriksadaftar;
    private $komentar;
    private $pengirim;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $tglBuat;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $tglSelesai;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\StatusSurat")
     * @ORM\JoinColumns({
     *   @ORM\JoinColumn(name="idSuratStatus", referencedColumnName="id")
     * })
     */
    private $IdSuratStatus;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $pengirimNamaText;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $reject_step;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNoSuratRt(): ?string
    {
        return $this->noSuratRt;
    }

    public function setNoSuratRt(string $noSuratRt): self
    {
        $this->noSuratRt = $noSuratRt;

        return $this;
    }

    public function getNoSuratRw(): ?string
    {
        return $this->noSuratRw;
    }

    public function setNoSuratRw(string $noSuratRw): self
    {
        $this->noSuratRw = $noSuratRw;

        return $this;
    }

    public function getBodySurat(): ?string
    {
        return $this->bodySurat;
    }

    public function setBodySurat(string $bodySurat): self
    {
        $this->bodySurat = $bodySurat;

        return $this;
    }

    public function getStep(): ?int
    {
        return $this->step;
    }

    public function setStep(int $step): self
    {
        $this->step = $step;

        return $this;
    }

    public function getNoSuratKeterangan(): ?string
    {
        return $this->noSuratKeterangan;
    }

    public function setNoSuratKeterangan(string $noSuratKeterangan): self
    {
        $this->noSuratKeterangan = $noSuratKeterangan;

        return $this;
    }

    public function getKeterangan(): ?string
    {
        return $this->keterangan;
    }

    public function setKeterangan(?string $keterangan): self
    {
        $this->keterangan = $keterangan;

        return $this;
    }

    public function getTglSelesaiRT(): ?\DateTimeInterface
    {
        return $this->tglSelesaiRT;
    }

    public function setTglSelesaiRT(?\DateTimeInterface $tglSelesaiRT): self
    {
        $this->tglSelesaiRT = $tglSelesaiRT;

        return $this;
    }

    public function getTglSelesaiRW(): ?\DateTimeInterface
    {
        return $this->tglSelesaiRW;
    }

    public function setTglSelesaiRW(?\DateTimeInterface $tglSelesaiRW): self
    {
        $this->tglSelesaiRW = $tglSelesaiRW;

        return $this;
    }

    public function getTglSelesaiKelurahan(): ?\DateTimeInterface
    {
        return $this->tglSelesaiKelurahan;
    }

    public function setTglSelesaiKelurahan(?\DateTimeInterface $tglSelesaiKelurahan): self
    {
        $this->tglSelesaiKelurahan = $tglSelesaiKelurahan;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getPemohonSurat(): ?Penduduk
    {
        return $this->pemohonSurat;
    }

    public function setPemohonSurat(?Penduduk $pemohonSurat): self
    {
        $this->pemohonSurat = $pemohonSurat;

        return $this;
    }

    public function getNoPengajuan(): ?string
    {
        return $this->noPengajuan;
    }

    public function setNoPengajuan(string $noPengajuan): self
    {
        $this->noPengajuan = $noPengajuan;

        return $this;
    }

    public function getTipe(): ?int
    {
        return $this->Tipe;
    }

    public function setTipe(int $Tipe): self
    {
        $this->Tipe = $Tipe;

        return $this;
    }

    public function getTembusandaftar()
    {
        return $this->tembusandaftar;
    }

    public function setTembusandaftar($tembusandaftar)
    {
        $this->tembusandaftar =$tembusandaftar;
    }

    public function getKepadadaftar()
    {
        return $this->kepadadaftar;
    }

    public function setKepadadaftar($kepadadaftar)
    {
        $this->kepadadaftar = $kepadadaftar;
    }

    public function getPemeriksadaftar()
    {
        return $this->pemeriksadaftar;
    }

    public function setPemeriksadaftar($pemeriksadaftar)
    {
        $this->pemeriksadaftar = $pemeriksadaftar;
    }

    public function getKomentar()
    {
        return $this->komentar;
    }

    public function setKomentar($komentar)
    {
        $this->komentar = $komentar;
    }

    public function getTglBuat(): ?\DateTimeInterface
    {
        return $this->tglBuat;
    }

    public function setTglBuat(?\DateTimeInterface $tglBuat): self
    {
        $this->tglBuat = $tglBuat;

        return $this;
    }

    public function getTglSelesai(): ?\DateTimeInterface
    {
        return $this->tglSelesai;
    }

    public function setTglSelesai(?\DateTimeInterface $tglSelesai): self
    {
        $this->tglSelesai = $tglSelesai;

        return $this;
    }

    public function getIdSuratStatus(): ?StatusSurat
    {
        return $this->IdSuratStatus;
    }

    public function setIdSuratStatus(?StatusSurat $IdSuratStatus): self
    {
        $this->IdSuratStatus = $IdSuratStatus;

        return $this;
    }

    public function getPengirimNamaText(): ?string
    {
        return $this->pengirimNamaText;
    }

    public function setPengirimNamaText(?string $pengirimNamaText): self
    {
        $this->pengirimNamaText = $pengirimNamaText;

        return $this;
    }

    public function getPengirim()
    {
        return $this->pengirim;
    }

    public function setPengirim($pengirim)
    {
        $this->pengirim = $pengirim;
    }

    public function getRejectStep(): ?int
    {
        return $this->reject_step;
    }

    public function setRejectStep(?int $reject_step): self
    {
        $this->reject_step = $reject_step;

        return $this;
    }
}

src/Controller/SuratKeteranganController.php
<?php

namespace App\Controller;

use App\Entity\NdSurat;
use App\Entity\Penduduk;
use App\Service\suratService;
use App\Service\userInfo;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

class SuratKeteranganController extends AbstractController
{
    /**
     * @Route("/surat/keterangan", name="surat_keterangan")
     */
    public function index(suratService $service,userInfo $userInfo)
    {
        $idUser= $this->getUser()->getId();
        $jabatan = $userInfo->getJabatan($idUser)->getIdJobPosition()->getId();
        $datas = $service->suratberjalanKeterangan($jabatan,$idUser);
        return $this->render('surat_keterangan/index.html.twig',['datas'=>$datas]);
    }

    /**
     * @Route("/detailSk{id}", name="detailSk", methods={"GET","POST"})
     */
    public function detailSK($id,suratService $service,Request $request)
    {
        $ad = $this->getDoctrine()->getRepository(NdSurat::class)->findOneBy(['id'=>$id]);
        $form = $this->createFormBuilder($ad)
            ->add('noSuratRt',TextType::class, ['label'=>false,'attr'=>['class'=>'form-control','placeholder'=>'noSuratRt']])
            ->add('noSuratRw',TextType::class, ['label'=>false,'attr'=>['class'=>'form-control','placeholder'=>'noSuratRW']])
            ->add('noSuratKeterangan',TextType::class, ['label'=>false,'required'=>false,'attr'=>['class'=>'form-control','placeholder'=>'noSuratKeterangan']])
            ->add('keterangan',TextType::class, ['label'=>false,'attr'=>['class'=>'form-control','placeholder'=>'keterangan']])
            ->add('pemohonSurat',EntityType::class,[
                'attr'=>['class'=>'form-control'],
                'class'=>Penduduk::class,
                'choice_label'=>'namaPenduduk'
            ])
            ->add('noPengajuan',TextType::class, ['label'=>false,'attr'=>['class'=>'form-control','placeholder'=>'noPengajuan']])
            ->add('Tipe',TextType::class, ['label'=>false,'attr'=>['class'=>'form-control','placeholder'=>'Tipe']])
            ->add('bodySurat',TextareaType::class, ['label'=>false,'attr'=>['class'=>'form-control','placeholder'=>'body']])
            ->add('komentar',TextType::class, ['label'=>false,'attr'=>['class'=>'form-control','placeholder'=>'Komentar']])
            ->add('approveSK', SubmitType::class, ['attr' => ['class' => 'btn btn-primary mt-3 ml-3', 'style' => 'float: left'], 'label' => 'Approve'])
            ->add('rejectSK', SubmitType::class, ['attr' => ['class' => 'btn btn-primary mt-3 ml-3', 'style' => 'float: left'], 'label' => 'Return'])
           ->getForm();
        $form->handleRequest($request);
        if($form->getClickedButton()=== $form->get('approveSK'))
        {
            $datas = $form->getData();
            $service->approveSk($datas);
        }
        elseif($form->getClickedButton()== $form->get('rejectSK'))
        {
            $datas = $form->getData();
            $service->submiSurat($datas);
        }
        return $this->render('surat_keterangan/detailSK.html.twig', array('form' => $form->createView()));
    }
}

templates/surat_keterangan/detailSK.html.twig
{% extends 'base.html.twig' %}
{% block title %}
{% endblock %}
{% block body %}
    <div class="container">
        {{ form_start(form) }}
        <div class="mt-5 border mb-4 pt-4 pb-4 pl-5">
            <div class="form-group row">
                <label for="colFormLabelSm" class="col-sm-2 col-form-label col-form-label-sm"><b>NoSurat RT</b></label>
                <div class="col-sm-10">
                    {{ form_row(form.noSuratRt) }}
                </div>
            </div>
            <div class="form-group row">
                <label for="colFormLabelSm" class="col-sm-2 col-form-label col-form-label-sm"><b>NoSurat Rw</b></label>
                <div class="col-sm-10">
                    {{ form_row(form.noSuratRw) }}
                </div>
            </div>
            <div class="form-group row">
                <label for="colFormLabelSm" class="col-sm-2 col-form-label col-form-label-sm"><b>No Keterangan</b></label>
                <div class="col-sm-10">
                    {{ form_row(form.noSuratKeterangan) }}
                </div>
            </div>
            <div class="form-group row">
                <label for="colFormLabelSm" class="col-sm-2 col-form-label col-form-label-sm"><b>Keterangan</b></label>
                <div class="col-sm-10">
                    {{ form_row(form.keterangan) }}
                </div>
            </div>
            <div class="form-group row">
                <label for="colFormLabelSm" class="col-sm-2 col-form-label col-form-label-sm"><b>Pemohon Surat</b></label>
                <div class="col-sm-10">
                    {{ form_row(form.pemohonSurat) }}
                </div>
            </div>
            <div class="form-group row">
                <label for="colFormLabelSm" class="col-sm-2 col-form-label col-form-label-sm"><b>No Pengajuan</b></label>
                <div class="col-sm-10">
                    {{ form_row(form.noPengajuan) }}
                </div>
            </div>
            <div class="form-group row">
                <label for="colFormLabelSm" class="col-sm-2 col-form-label col-form-label-sm"><b>Tipe Surat Keterangan</b></label>
                <div class="col-sm-10">
                    {{ form_row(form.Tipe) }}
                </div>
            </div>
            <div class="form-group row">
                <label for="colFormLabelSm" class="col-sm-2 col-form-label col-form-label-sm"><b>Body Surat</b></label>
                <div class="col-sm-10">
                    {{ form_row(form.bodySurat) }}
                </div>
            </div>
            <div class="form-group row">
                <label for="colFormLabelSm" class="col-sm-2 col-form-label col-form-label-sm"><b>Komentar</b></label>
                <div class="col-sm-10">
                    {{ form_row(form.komentar) }}
                </div>
            </div>
            <div class="form-group row">
                {{ form_row(form.approveSK) }}
                {{ form_row(form.rejectSK) }}
            </div>
        </div>
        {{ form_end(form) }}
    </div>
    <script  src="{{ asset('/assets/plugins/tinymce/tinymce.min.js') }}"></script>
    <script src="{{ asset('/assets/plugins/tinymce/init-tinymce.js') }}"></script>
{% endblock %}

templates/surat_keterangan/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello SuratKeteranganController!{% endblock %}

{% block body %}
   <table class="table table-hover">
      <thead>
      <tr>
         <th>Keterangan</th>
         <th>Nama Pemohon Surat</th>
         <th>Jenis Surat Pemohon</th>
         <th>Detail</th>
      </tr>
      </thead>
      <tbody>
      {% for data in datas %}
         <tr>
            <td >{{ data.refid.keterangan('d-m-Y H:i:s') }}</td>
            <td>{{ data.refid.pemohonSurat.namaPenduduk }}</td>
               {% if (data.refid.tipe == 1)%}
                 <td>Surat Keterangan Tidak Mampu (SKTM)</td>
               {% endif %}
               {% if (data.refid.tipe == 2) %}
                  <td>Surat Keterangan Usaha(SKU)</td>
               {% endif %}
               {% if(data.refid.tipe == 3) %}
                  <td>Surat Penghantar Keramaian</td>
               {% endif %}
               {% if(data.refid.tipe == 4) %}
                  <td>Surat Keterangan Cerai Hidup / Mati</td>
               {% endif %}
               {% if(data.refid.tipe == 5) %}
                  <td>Surat Keterangan Keterangan Domisili</td>
               {% endif %}
               {% if(data.refid.tipe == 6) %}
                  <td>Surat Keterangan Kematian</td>
               {% endif %}
               {% if(data.refid.tipe == 7) %}
                  <td>Surat Keterangan pindah(Keluar/Datang)</td>
               {% endif %}
            <td>
               <a href="{{ path('detailSk',{'id':data.refid.id}) }}">detail</a>
            </td>
         </tr>
      {% endfor %}
      </tbody>
   </table>
{% endblock %}